# Generate rum-config.js from .env file
# This script reads DD_RUM_* variables from the .env file and creates a rum-config.js file

$ErrorActionPreference = "Stop"

# Get the root directory (one level up from ApiFramework)
$rootDir = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $rootDir ".env"
$outputFile = Join-Path $PSScriptRoot "rum-config.js"

Write-Host "Script directory: $PSScriptRoot"
Write-Host "Root directory: $rootDir"
Write-Host "Looking for .env at: $envFile"
Write-Host "Output file: $outputFile"
Write-Host ""

# Check if .env file exists
if (-not (Test-Path $envFile)) {
    Write-Warning ".env file not found at $envFile"
    Write-Warning "Creating empty rum-config.js with defaults"

    $emptyConfig = @"
// RUM Configuration (generated from .env)
window.DD_RUM_CONFIG = {
    enabled: true,
    clientToken: '',
    applicationId: '',
    site: 'datadoghq.com',
    service: 'datadog-maui-web-framework',
    env: 'dev',
    version: '1.0.0',
    sessionSampleRate: 100,
    sessionReplaySampleRate: 100,
    trackBfcacheViews: true,
    defaultPrivacyLevel: 'mask-user-input',
    allowedTracingUrls: ["localhost", "127.0.0.1", (url) => { return true; }]
};
console.warn('[Datadog] RUM config loaded with empty credentials - check .env file');
"@

    Set-Content -Path $outputFile -Value $emptyConfig
    exit 0
}

# Read .env file and parse DD_RUM_* variables
$rumConfig = @{
    clientToken = ''
    applicationId = ''
    service = 'datadog-maui-web-framework'
    site = 'datadoghq.com'
    env = 'prod'
    version = '1.0.0'
}

Get-Content $envFile | ForEach-Object {
    $line = $_.Trim()

    # Skip comments and empty lines
    if ($line -match '^#' -or $line -eq '') {
        return
    }

    # Parse key=value pairs
    if ($line -match '^([^=]+)=(.*)$') {
        $key = $matches[1].Trim()
        $value = $matches[2].Trim()

        # Map environment variables to RUM config
        switch ($key) {
            'DD_RUM_WEB_CLIENT_TOKEN' { $rumConfig.clientToken = $value }
            'DD_RUM_WEB_APPLICATION_ID' { $rumConfig.applicationId = $value }
            'DD_RUM_WEB_SERVICE' { $rumConfig.service = $value }
            'DD_SITE' { $rumConfig.site = $value }
            'DD_ENV' { $rumConfig.env = $value }
            'DD_VERSION' { $rumConfig.version = $value }
        }
    }
}

# Generate JavaScript config file
$clientToken = $rumConfig['clientToken']
$applicationId = $rumConfig['applicationId']
$site = $rumConfig['site']
$envName = $rumConfig['env']
$service = $rumConfig['service']
$version = $rumConfig['version']

$jsConfig = @"
// RUM Configuration (generated from .env)
// DO NOT EDIT THIS FILE DIRECTLY - it is auto-generated during build
window.DD_RUM_CONFIG = {
    enabled: true,
    clientToken: '$clientToken',
    applicationId: '$applicationId',
    site: '$site',
    service: '$service',
    env: '$envName',
    version: '$version',
    sessionSampleRate: 100,
    sessionReplaySampleRate: 100,
    trackBfcacheViews: true,
    defaultPrivacyLevel: 'mask-user-input',
    allowedTracingUrls: ["localhost", "127.0.0.1", (url) => { return true; }]
};
console.log('[Datadog] RUM config loaded from .env file');
"@

# Write the config file
Set-Content -Path $outputFile -Value $jsConfig

Write-Host "Generated rum-config.js successfully" -ForegroundColor Green
if ($clientToken.Length -gt 0) {
    $tokenPreview = $clientToken.Substring(0, [Math]::Min(20, $clientToken.Length))
    Write-Host "  Client Token: ${tokenPreview}..."
}
Write-Host "  Application ID: ${applicationId}"
Write-Host "  Service: ${service}"
Write-Host "  Site: ${site}"
Write-Host "  Environment: ${envName}"
Write-Host "  Version: ${version}"
