using System.IO;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Http;

namespace DatadogMauiApi.Framework.Controllers
{
    [RoutePrefix("")]
    public class RumConfigController : ApiController
    {
        [HttpGet]
        [Route("rum-config.js")]
        public HttpResponseMessage GetRumConfig()
        {
            // Serve the rum-config.js file that was generated during build
            // The file is generated by generate-rum-config.ps1 from .env variables
            var rumConfigPath = Path.Combine(HttpContext.Current.Server.MapPath("~"), "rum-config.js");

            string jsConfig;

            if (File.Exists(rumConfigPath))
            {
                jsConfig = File.ReadAllText(rumConfigPath);
            }
            else
            {
                // Fallback if file doesn't exist (shouldn't happen after build)
                jsConfig = @"// RUM Configuration file not found
console.warn('[Datadog] rum-config.js not found. Run build to generate from .env file.');
window.DD_RUM_CONFIG = {
    clientToken: '',
    applicationId: '',
    site: 'datadoghq.com',
    service: 'datadog-maui-web-framework',
    env: 'local',
    version: '1.0.0',
    sessionSampleRate: 100,
    sessionReplaySampleRate: 100,
    trackBfcacheViews: true,
    defaultPrivacyLevel: 'mask-user-input',
    allowedTracingUrls: ['localhost', '127.0.0.1']
};";
            }

            var response = new HttpResponseMessage(HttpStatusCode.OK);
            response.Content = new StringContent(jsConfig, Encoding.UTF8, "application/javascript");
            return response;
        }
    }
}
